### ISSUE TITLE
Missing folder and file for training

### ISSUE THREAD

**Issue by CheeGY** [ntnu-arl/colpred_nmpc#1]
Hi! 

Thanks for sharing your code! I'm trying to train a model using the script "depth_state_check_train.py", but ran into an missing-file error, which requires a folder "collision_dat" and a file "half_clutter.yaml".

Would you be able to provide the data required for training, or the trained model so that the results in your paper can be replicated?

Thanks!

**Comment by sedith** [comment]
I was supposed to upload those on a drive but kept postponing it, my apologies.
I will do it as soon as possible and update this issue and the readme accordingly.

**Comment by sedith** [comment]
The training/testing data (in a tar.gz) are accessible through this link: https://ntnu.box.com/v/colpred-nmpc-dataset
One need to modify the path to the folder where the data in unzipped in this line https://github.com/ntnu-arl/colpred_nmpc/blob/ff2df9dd0d5d8c3e56cf4f3bbedfcd49e5083455/colpred_nmpc/__init__.py#L4 ; then the rest *should* work seamlessly.

sorry again for this long overdue upload!

**Comment by CheeGY** [comment]
Hi,

Thanks again for the files. 

I tried to run depth_state_check_train.py, but ran into an issue where the training dataset, half_clutter_train.hdf5, only contains ['raw'], but not ['collision'].

Also, I would need to change the parameters hdf5_train and hdf5_test in half_clutter.yaml to half_clutter_train.hdf5 and half_clutter_test.hdf5 respectively, so that it is compatible with the files in the link given above.
